server:
  port: 8087
  servlet:    context-path: /restaurant
spring:  application:    name: restaurant-service
    datasource:    url: jdbc:mysql://localhost:3306/uber_eats_restaurant
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:    database: MYSQL    hibernate:      ddl-auto: none
      
    show-sql: true