server:
  port: 8085
  servlet:    context-path: /pay
spring:  application:    name: payment-service
    datasource:    url: jdbc:mysql://localhost:3306/uber_eats_payment
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:    database: MYSQL    hibernate:      ddl-auto: none
      
    show-sql: true