server:
  port: 8081
  servlet:    context-path: /delivery
spring:  application:    name: delivery-service
    datasource:    url: jdbc:mysql://localhost:3306/uber_eats_order
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:    database: MYSQL    hibernate:      ddl-auto: none
      
    show-sql: true